services:
  - type: web
    name: line-stock-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: CHANNEL_SECRET
        fromEnv: CHANNEL_SECRET
      - key: CHANNEL_ACCESS_TOKEN
        fromEnv: CHANNEL_ACCESS_TOKEN
      - key: RENDER_EXTERNAL_HOSTNAME
        fromEnv: RENDER_EXTERNAL_HOSTNAME
